const analysisData = {
  "title": "Analysis of Candy Policy Document Changes (v0 to v1)",
  "statistics": { "additions": 14, "deletions": 4, "modifications": 8 },
  "analysis": {
    "summaryOfChanges": "The revised document (v1) significantly expands upon the original version (v0). The changes primarily focus on adding greater detail, more descriptive language, and additional context across all sections. The historical background is more thorough, descriptions of candy types are more vivid, and the cultural significance section includes more specific examples and addresses modern industry trends like health consciousness.",
    "themesAndTopics": [
      { "theme": "History of Candy", "description": "Both versions cover the ancient origins and the impact of sugar production. Version 1 provides more specific details on early sweeteners and the timeline of industrial development." },
      { "theme": "Candy Categories", "description": "A review of different candy types like hard, chewy, and chocolate. Version 1 uses more descriptive adjectives and elaborates on the consumer experience of each type, while also refining the list of examples." },
      { "theme": "Cultural Significance", "description": "Discusses candy's role in holidays and society. Version 1 expands on this by connecting candy to memories, social rituals, and specific holiday traditions, and also introduces the topic of modern health-conscious innovations." }
    ],
    "narrativeOfChanges": "The document revision process from v0 to v1 involved a comprehensive enhancement of the existing text. The introduction was enriched with more engaging language and a more detailed historical account, specifying the 19th and 20th centuries as the key period for industrial growth. In the section on candy categories, the descriptions were made more evocative; for instance, hard candies are now described as 'offering long-lasting flavor,' and the textural differences between caramels and gummies are articulated. The original version's simple list of 'licorice, sour candies, and chewing gum' was replaced with a more descriptive sentence, and 'chewing gum' was removed. The final paragraph on cultural significance saw the most significant expansion, with added details on the emotional and social roles of candy and more specific examples for holiday associations. A new concluding thought was added to address the industry's response to health trends, including the rise of sugar-free and artisanal products."
  },
  "tableOfChanges": [
    { "type": "Modification", "section": "Introduction", "originalText": "Candy, a broad term for confectionery, encompasses a diverse range of sweet treats primarily made from sugar or sugar substitutes.", "revisedText": "Candy, a broad term for confectionery and a near-universal delight, encompasses a diverse range of sweet treats primarily composed of sugar or sugar substitutes." },
    { "type": "Modification", "section": "Introduction", "originalText": "The history of candy dates back to ancient civilizations, where people enjoyed confections made from honey, fruits, and nuts.", "revisedText": "The history of candy stretches back to ancient civilizations, where people first satisfied their sweet cravings with confections made from honey, fruits, and nuts." },
    { "type": "Addition", "section": "Introduction", "originalText": null, "revisedText": "These early forms relied heavily on natural sweeteners available locally." },
    { "type": "Modification", "section": "Introduction", "originalText": "The large-scale production and accessibility of candy significantly increased with the cultivation of sugarcane and sugar beets, leading to the development of countless varieties through industrial processes.", "revisedText": "The large-scale production and accessibility of candy significantly increased with the widespread cultivation of sugarcane and sugar beets. This agricultural shift made refined sugar affordable, leading to the development of countless varieties through industrial processes during the 19th and 20th centuries." },
    { "type": "Addition", "section": "Candy Categories", "originalText": null, "revisedText": "..., demonstrating remarkable innovation." },
    { "type": "Modification", "section": "Candy Categories", "originalText": "Hard candies, like lollipops and brittles, are created by boiling sugar syrups to high temperatures.", "revisedText": "Hard candies, like lollipops and brittles, are created by boiling sugar syrups to high temperatures until they solidify, offering long-lasting flavor as they slowly dissolve." },
    { "type": "Addition", "section": "Candy Categories", "originalText": null, "revisedText": "Caramels provide a rich, buttery experience, while gummies offer fruity resilience." },
    { "type": "Modification", "section": "Candy Categories", "originalText": "Chocolate, perhaps the most celebrated category, spans from rich dark chocolate to sweet milk chocolate...", "revisedText": "Chocolate, perhaps the most celebrated category, spans from complex dark chocolate to sweet milk chocolate..." },
    { "type": "Modification", "section": "Candy Categories", "originalText": "Other significant types include licorice, sour candies, and chewing gum.", "revisedText": "The spectrum also includes piquant sour candies that challenge the palate and aromatic licorice varieties." },
    { "type": "Modification", "section": "Cultural Significance", "originalText": "Beyond being a simple treat, candy holds cultural significance worldwide.", "revisedText": "Beyond being a simple source of sweetness, candy holds significant cultural weight worldwide." },
    { "type": "Addition", "section": "Cultural Significance", "originalText": null, "revisedText": "Often tied to childhood memories and reward, it functions as a key element in social gatherings and personal rituals." },
    { "type": "Modification", "section": "Cultural Significance", "originalText": "It is closely associated with holidays such as Halloween, Easter, Valentine's Day, and Christmas, frequently used for gifts, decorations, and celebratory rituals.", "revisedText": "It is closely associated with holidays such as Halloween trick-or-treating, Easter baskets, Valentine's Day gifts, and Christmas stockings, frequently used for gifts and celebratory traditions." },
    { "type": "Deletion", "section": "Candy Categories", "originalText": "and chewing gum.", "revisedText": null },
    { "type": "Addition", "section": "Cultural Significance", "originalText": null, "revisedText": "In response to growing health consciousness, the industry continually innovates, offering sugar-free alternatives and artisanal creations using high-quality ingredients." }
  ],
  "documents": {
    "version0": { "fileName": "Candy v0 - 09 Sep 2024.docx", "fullText": "Candy, a broad term for confectionery, encompasses a diverse range of sweet treats primarily made from sugar or sugar substitutes. The history of candy dates back to ancient civilizations, where people enjoyed confections made from honey, fruits, and nuts. The large-scale production and accessibility of candy significantly increased with the cultivation of sugarcane and sugar beets, leading to the development of countless varieties through industrial processes.\n\nToday, candy categories cater to a wide array of tastes and textures. Hard candies, like lollipops and brittles, are created by boiling sugar syrups to high temperatures. Chewy candies include popular options such as caramels, taffy, gummies, and marshmallows, offering varying degrees of softness and elasticity. Chocolate, perhaps the most celebrated category, spans from rich dark chocolate to sweet milk chocolate and creamy white chocolate, often enhanced with nuts, fruits, or fillings like nougat. Other significant types include licorice, sour candies, and chewing gum.\n\nBeyond being a simple treat, candy holds cultural significance worldwide. It is closely associated with holidays such as Halloween, Easter, Valentine's Day, and Christmas, frequently used for gifts, decorations, and celebratory rituals. While candy brings pleasure, its high sugar content generally means it is best enjoyed in moderation as part of a balanced diet." },
    "version1": { "fileName": "Candy v1 - 09 Sep 2025.docx", "fullText": "Candy, a broad term for confectionery and a near-universal delight, encompasses a diverse range of sweet treats primarily composed of sugar or sugar substitutes. The history of candy stretches back to ancient civilizations, where people first satisfied their sweet cravings with confections made from honey, fruits, and nuts. These early forms relied heavily on natural sweeteners available locally. The large-scale production and accessibility of candy significantly increased with the widespread cultivation of sugarcane and sugar beets. This agricultural shift made refined sugar affordable, leading to the development of countless varieties through industrial processes during the 19th and 20th centuries.\n\nToday, candy categories cater to a wide array of tastes and textures, demonstrating remarkable innovation. Hard candies, like lollipops and brittles, are created by boiling sugar syrups to high temperatures until they solidify, offering long-lasting flavor as they slowly dissolve. Chewy candies include popular options such as caramels, taffy, gummies, and marshmallows, offering varying degrees of softness and elasticity. Caramels provide a rich, buttery experience, while gummies offer fruity resilience. Chocolate, perhaps the most celebrated category, spans from complex dark chocolate to sweet milk chocolate and creamy white chocolate, often enhanced with nuts, fruits, or fillings like nougat. The spectrum also includes piquant sour candies that challenge the palate and aromatic licorice varieties.\n\nBeyond being a simple source of sweetness, candy holds significant cultural weight worldwide. Often tied to childhood memories and reward, it functions as a key element in social gatherings and personal rituals. It is closely associated with holidays such as Halloween trick-or-treating, Easter baskets, Valentine's Day gifts, and Christmas stockings, frequently used for gifts and celebratory traditions. While candy brings immense pleasure, its typically high sugar content necessitates consumption in moderation as part of a balanced diet. In response to growing health consciousness, the industry continually innovates, offering sugar-free alternatives and artisanal creations using high-quality ingredients." }
  }
};
